module.exports = {
  src: {
    html: "src/html/pages/**/*.+(html|nunjucks)",
    css: "src/assets/scss/*.scss",
    js: "src/assets/js/**/*.js",
    images: "src/assets/images/**/*",
    video: "src/assets/video/**/*",
    fonts: "src/assets/fonts/**/*",
    data: "src/json/*",
    db: "src/json/map-style.json",
    php: "src/**/*.php",
    crm: "src/crm/*",
  },
  watch: {
    html: "src/html/**/*.html",
    css: "src/assets/scss/**/*.scss",
    js: "src/assets/js/**/*.js",
    images: "src/assets/images/**/*",
    video: "src/assets/video/**/*",
    fonts: "src/assets/fonts/**/*",
    data: "src/json/data.json",
    db: "src/json/map-style.json",
    crm: "src/crm/*",
  },
  build: {
    html: "build/",
    css: "build/assets/css/",
    js: "build/assets/js/",
    fonts: "build/assets/fonts/",
    images: "build/assets/images/",
    video: "build/assets/video/",
    db: "build/assets/json/",
    php: "build/",
    crm: "build/crm/",
  },
  clean: "build/",
};
